### ISSUE TITLE
Printing...

### ISSUE THREAD

**Issue by zkiwi34** [tonybolzan/snap-mysql-workbench#1]
What do I do to get mysql-workbench-community to see/connect to printers?

I have tried snap connect mysql-workbench-community:cups-control

Is it even possible?

**Comment by tonybolzan** [comment]
I added the interface cups-control to building processes of snapcraft on version 8.0.22
But I don't have a printer to test, please install new version and test
```sh
snap install mysql-workbench-community --edge

snap connect mysql-workbench-community:password-manager-service 
snap connect mysql-workbench-community:ssh-keys
snap connect mysql-workbench-community:cups-control
```

**Comment by zkiwi34** [comment]
I added the connect, did the refresh, and printed an EER diagram.

Works as expected! 👍 
Thank you.

**Comment by tonybolzan** [comment]
Thanks for the feedback... I will promote the edge to stable

**Comment by zkiwi34** [comment]
However... as I poked around a bit more, the data from my sample tables all came up as null or an empty block [] character.

Flip back to stable, printing vanishes as expected, data comes back visible and checks out.
