### ISSUE TITLE
can't connect to database

### ISSUE THREAD

**Issue by bsutton** [tonybolzan/snap-mysql-workbench#17]
Each time I try to connect it crashes.

```
sudo snap install mysql-workbench-community --classic
Warning: flag --classic ignored for strictly confined snap mysql-workbench-community

mysql-workbench-community 8.0.29 from Tonin Bolzan (tonybolzan) installed
```

The `strictly-confined` seems problematic  as you need access to the keystore which app armour doesn't allow.
Ignore that problem...

Starting workbench
``
mysql-workbench-community 
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Using /snap/mysql-workbench-community/10/usr/lib/x86_64-linux-gnu/libproj.so.
Gtk-Message: 15:15:47.848: Failed to load module "xapp-gtk3-module"
Gtk-Message: 15:15:47.927: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:15:47.936: Failed to load module "canberra-gtk-module"

```

When I try to connect to a database I get an app armour error.

My undestanding is that the snap needs --classic but as per the install above the --classic switch is ignored.


ubuntu 22.10

**Comment by brezniczky** [comment]
If this is still a problem, maybe try installing via

`snap install mysql-workbench-community`

and then do a

`snap connect mysql-workbench-community:password-manager-service`

If you're uncertain what I'm talking about, so am I, but fret not, this may explain:
https://snapcraft.io/docs/auto-connection-mechanism

**Comment by tonybolzan** [comment]
Possible fixed in https://github.com/tonybolzan/snap-mysql-workbench/pull/15
Please update to latest version
```sh
sudo snap remove mysql-workbench-community
sudo snap install mysql-workbench-community --edge
sudo snap connect mysql-workbench-community:password-manager-service
sudo snap connect mysql-workbench-community:ssh-keys
sudo snap connect mysql-workbench-community:cups-control
sudo snap connect mysql-workbench-community:removable-media

snap run mysql-workbench-community
```
