### ISSUE TITLE
Falta de Icones e Fechando sozinho

### ISSUE THREAD

**Issue by danielmota** [tonybolzan/snap-mysql-workbench#18]
Salve \o)

Durante a modelagem ER ao selecionar para fechar as propriedades da tabela, a aplicação simplesmente fecha.

Durente o uso, vejo faltar alguns icones, principalmente de fechar das abas

Ao rodar por cli tenho a saída em anexo.

[debian11_mysql_workbench_debug.log](https://github.com/tonybolzan/snap-mysql-workbench/files/10844880/debian11_mysql_workbench_debug.log)

Nela há a lista de snaps instalados.

Estou usando o Debian 11 totalmente atualizado.

**Comment by tonybolzan** [comment]
O erro que você esta recebendo é um `Segmentation fault` do MySQL Workbench, eu não tenho nenhum envolvimento com o time que desenvolve na Oracle, porém eu atualizei este snap para a última versão [8.2.32](https://github.com/tonybolzan/snap-mysql-workbench/pull/15) que provavelmente resolve o seu problema.

Realiza a atualização e me avisa se o problema foi resolvido
```sh
sudo snap remove mysql-workbench-community
sudo snap install mysql-workbench-community --edge
sudo snap connect mysql-workbench-community:password-manager-service
sudo snap connect mysql-workbench-community:ssh-keys
sudo snap connect mysql-workbench-community:cups-control
sudo snap connect mysql-workbench-community:removable-media

snap run mysql-workbench-community
```

**Comment by danielmota** [comment]
Opa! Obrigado pelo feedback.

Não estou mais usando tal versão no Debian/Snap.
Vou ver se consigo montar um cenário de testes para dar esse feedback, não
garanto.

Existe a hipótese de sair uma versão para Flatpak?
Não sei se notou, mas havia erros de falta de icones, que citei e constavam
no log anexado.

*Atenciosamente, Daniel Mota*
MBA em Análise de Sistemas e Telecomunicações


*DOM - Especialista em Tecnologia da Informação*CNPJ: 35.967.691/0001-81

Contatos: (75) 99155-0101 / 99210-0070
Telegram: @danielmota
https://dom.eti.br | https://about.me/danielmota

*Ps:* Se não for o destinatário deste email, por favor responda-me para ter
ciência e desconsidere-o ;)


Em qui., 13 de abr. de 2023 às 18:44, Tonin Bolzan ***@***.***>
escreveu:
