### ISSUE TITLE
8.0.36 available

### ISSUE THREAD

**Issue by faveoled** [tonybolzan/snap-mysql-workbench#19]
Please trigger a rebuild

**Comment by tonybolzan** [comment]
Builded in edge channel `sudo snap install mysql-workbench-community --edge`
Please test and report to elevate to stable channel

**Comment by faveoled** [comment]
![Screenshot from 2024-02-01 14-17-46](https://github.com/tonybolzan/snap-mysql-workbench/assets/85760289/724ff393-1a8a-44d0-a643-b44598788bf5)
Mostly works but there's o segfault Database -> Connect to database -> Ok:
```
(mysql-workbench-bin:13701): Gtk-CRITICAL **: 14:17:36.828: gtk_tree_view_unref_tree_helper: assertion 'node != NULL' failed
/snap/mysql-workbench-community/13/usr/bin/mysql-workbench: line 108: 13701 Segmentation fault      (core dumped) $MWB_BINARIES_DIR/mysql-workbench-bin "$@"
```
