### ISSUE TITLE
mysql-workbench on debian without desktop enviroment

### ISSUE THREAD

**Issue by bambosd** [tonybolzan/snap-mysql-workbench#20]
Dear Developer,

i have a debian system with mysql server already running. 
on my effort to get a management interface for mysql, i install the snapd repository and then sudo snap install mysql-workbench-community. (since official mysql-workbench is for ubuntu and not working on debian because of dependencies).

After installation from snap, how we can execute the application ?? if it's a desktop app, does this mean that we need a desktop environment ? or is it a web service? (this debian system does not have desktop, only CLI)

Thanks for any suggestions !

**Comment by tonybolzan** [comment]
MySQL are a GUI application, and depends of a Xorg or Wayland to work. Is not intended to run on a server, but with a VNC/RDP technically you can run, but I don't recommend on a server without a Desktop Environment.

https://www.mysql.com/products/workbench/
