### ISSUE TITLE
App just closes when testing a connection through an ssh tunnel

### ISSUE THREAD

**Issue by 1000mb** [tonybolzan/snap-mysql-workbench#5]
When running it from the terminal I get this error:

```
(mysql-workbench-bin:29103): glibmm-ERROR **: 12:33:42.551: 
unhandled exception (type unknown) in signal handler

Trace/breakpoint trap (core dumped)
```

I've given it all the permissions (tried both from the permissions dialog in the software centre and from the cli)

I do get asked to confirm the server's public key fingerprint before it closes so it is doing something before the crash.

I've tried adjusting the permissions on the private key file needed for the connection and putting the file inside the snap's folder but that didn't change anything.

**Comment by tonybolzan** [comment]
Try edge version (8.0.23), this can be a Workbench bug
```
sudo snap install mysql-workbench-community --edge
```
I cannot upgraded the snap to version 8.0.25 because a incompatibility in the setup builder.

**Comment by 1000mb** [comment]
It's exactly the same with edge.

I've also tried connecting without a keyfile selected. This wouldn't be able to login as the server has password logins disabled but instead of giving me an error about a failed login it crashed again. Maybe it's more to do with the server it's trying to connect to? If it helps the server is a stock (as far as ssh goes) ubuntu 20.04 EC2 instance.

**Comment by tonybolzan** [comment]
I released a new version today
- WB upgraded to 8.0.25
- S/O Base upgraded to Ubuntu 20.04
- Connection for removable-media added

install with:
```sh
sudo snap install mysql-workbench-community --edge
sudo snap connect mysql-workbench-community:password-manager-service
sudo snap connect mysql-workbench-community:ssh-keys
sudo snap connect mysql-workbench-community:cups-control
sudo snap connect mysql-workbench-community:removable-media
```

**Comment by 1000mb** [comment]
That has done the trick! 

I can now connect to the remote server through ssh.

I wish there was a way you could get bug reports through the snap store. Since all you can do is add a review you've now got a bunch of 1 star reviews reporting exactly this problem. Seems I was the only person prepared to take the time to come to github and report it properly.

Thanks for your work.

**Comment by tonybolzan** [comment]
Thanks for helping to report the issue.
Unfortunately the snap store doesn't even have a way for me to respond to comments, or let everyone know about updates.
