### ISSUE TITLE
Cannot open files outside of home directory

### ISSUE THREAD

**Issue by cytech** [tonybolzan/snap-mysql-workbench#6]
opening a script stored under /mnt/scripts/something.sql results in permission denied error.
Can you add a connection for removable-media interface ?

**Comment by tonybolzan** [comment]
Of course I will, I'll work on it in the next few days along with the new version of the workbench.

**Comment by cytech** [comment]
great!
while im thinking about it (and nothing to do with above) there is an aggravating  interface issue in the snap.
on ubuntu 21.04,
when you select "Open SQL Script" and then select "Home" in the system open dialog. it drops you to
/home/user/snap/mysql-workbench-community/7
as the home directory and not /home/user.
you then have to select around a bunch to get to the actual home directory.
just a bit aggravating.
thanx

**Comment by tonybolzan** [comment]
I released a new version today
- WB upgraded to 8.0.25
- S/O Base upgraded to Ubuntu 20.04
- Connection for removable-media added

install with:
```sh
sudo snap install mysql-workbench-community --edge
sudo snap connect mysql-workbench-community:password-manager-service
sudo snap connect mysql-workbench-community:ssh-keys
sudo snap connect mysql-workbench-community:cups-control
sudo snap connect mysql-workbench-community:removable-media
```

**Comment by cytech** [comment]
perfect, thank you
