### ISSUE TITLE
Permissions issue on /proc/self/mountinfo

### ISSUE THREAD

**Issue by dave2309** [tonybolzan/snap-mysql-workbench#7]
When trying to setup  SSH connection I have this:
```
(mysql-workbench-bin:605487): GLib-GIO-WARNING **: 11:55:59.370: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

(mysql-workbench-bin:605487): glibmm-ERROR **: 11:56:27.016: 
unhandled exception (type unknown) in signal handler
```

Does anyone have something similar?

**Comment by tonybolzan** [comment]
Hi, David...
Please try to allow ssh permission and use the latest edge version
```sh
snap install mysql-workbench-community --edge
snap connect mysql-workbench-community:password-manager-service 
snap connect mysql-workbench-community:ssh-keys
```

**Comment by dave2309** [comment]
I did already
- install snap mysql-workbench-community
- connect all :)

**Comment by tonybolzan** [comment]
I can't reproduce this behaviour on Ubuntu 21.04 with X11
try running edge version with the command below to get more context of your error
```sh
snap run mysql-workbench-community --log-to-stderr
```

**Comment by dave2309** [comment]
Ok, that was a SSH key issue (wrong one)
the permissions message is not related to the crash directly. It occurs before attempting a connection, while setting the connection (clicking test connection for example)
So I could connect at the end.
Thanks for your support!

Regards,
David 

PS: wil close the issue.
