### ISSUE TITLE
mysql workbench close automatically when searching in a database

### ISSUE THREAD

**Issue by mohammedalrefai** [tonybolzan/snap-mysql-workbench#8]
OS : linux mint 20.2
mysql workbench : 8.0.22

I have issue with mysql workbench when I "search table data" it close immediatly after finshing the search.
any solution to this?

Thanks.

**Comment by tonybolzan** [comment]
Please try the latest edge version

```
snap install mysql-workbench-community --edge
```

**Comment by mohammedalrefai** [comment]
it works, thank you very much .
