### ISSUE TITLE
Unable to access a file provided through an sshfs

### ISSUE THREAD

**Issue by AnaelMobilia** [tonybolzan/snap-mysql-workbench#9]
Dear maintainers,

I'm unable to acces a file stored on a remote sshfs : I'm getting an error when browsing a file through the "Open Model" window :
```Could not read the contents of remote - Error opening directory '/home/user/remote/': Permission denied``` .

My environment is :
  - Ubuntu 22.04 LTS
  - Folder /home/user/remote
  - Remote filesystem is mounted on this folder via the command ```sshfs user@remote.server:/path/ /home/user/remote```
  - Permission on the /home/user/remote folder are 755

Snap informations : 
  - snapd v2.55.3
  - mysql-workbench-community v8.0.25
  - Executed commands : 
    - ```snap connect mysql-workbench-community:removable-media```
    - ```snap connect mysql-workbench-community:password-manager-service```
    - ```snap connect mysql-workbench-community:ssh-keys```

```snap connections mysql-workbench-community``` :
```Interface                 Connecteur                                          Prise                            Notes
content[gnome-3-38-2004]  mysql-workbench-community:gnome-3-38-2004           gnome-3-38-2004:gnome-3-38-2004  -
content[gtk-3-themes]     mysql-workbench-community:gtk-3-themes              gtk-common-themes:gtk-3-themes   -
content[icon-themes]      mysql-workbench-community:icon-themes               gtk-common-themes:icon-themes    -
content[sound-themes]     mysql-workbench-community:sound-themes              gtk-common-themes:sound-themes   -
cups-control              mysql-workbench-community:cups-control              -                                -
desktop                   mysql-workbench-community:desktop                   :desktop                         -
desktop-legacy            mysql-workbench-community:desktop-legacy            :desktop-legacy                  -
gsettings                 mysql-workbench-community:gsettings                 :gsettings                       -
home                      mysql-workbench-community:home                      :home                            -
network                   mysql-workbench-community:network                   :network                         -
opengl                    mysql-workbench-community:opengl                    :opengl                          -
password-manager-service  mysql-workbench-community:password-manager-service  :password-manager-service        manual
removable-media           mysql-workbench-community:removable-media           :removable-media                 manual
ssh-keys                  mysql-workbench-community:ssh-keys                  :ssh-keys                        manual
wayland                   mysql-workbench-community:wayland                   :wayland                         -
x11                       mysql-workbench-community:x11                       :x11                             -
```

For information, i'm able to access this folder through firefox (which is installed through snap too).
```snap connections firefox``` : 
```Interface                 Connecteur                      Prise                            Notes
audio-playback            firefox:audio-playback          :audio-playback                  -
audio-record              firefox:audio-record            :audio-record                    -
avahi-observe             firefox:avahi-observe           :avahi-observe                   -
browser-support           firefox:browser-sandbox         :browser-support                 -
camera                    firefox:camera                  :camera                          -
content[gnome-3-38-2004]  firefox:gnome-3-38-2004         gnome-3-38-2004:gnome-3-38-2004  -
content[gtk-3-themes]     firefox:gtk-3-themes            gtk-common-themes:gtk-3-themes   -
content[icon-themes]      firefox:icon-themes             gtk-common-themes:icon-themes    -
content[sound-themes]     firefox:sound-themes            gtk-common-themes:sound-themes   -
cups-control              firefox:cups-control            :cups-control                    -
dbus                      -                               firefox:dbus-daemon              -
desktop                   firefox:desktop                 :desktop                         -
desktop-legacy            firefox:desktop-legacy          :desktop-legacy                  -
gsettings                 firefox:gsettings               :gsettings                       -
hardware-observe          firefox:hardware-observe        :hardware-observe                -
home                      firefox:home                    :home                            -
joystick                  firefox:joystick                :joystick                        -
mpris                     -                               firefox:mpris                    -
network                   firefox:network                 :network                         -
network-observe           firefox:network-observe         -                                -
opengl                    firefox:opengl                  :opengl                          -
personal-files            firefox:dot-mozilla-firefox     :personal-files                  -
removable-media           firefox:removable-media         :removable-media                 -
screen-inhibit-control    firefox:screen-inhibit-control  :screen-inhibit-control          -
system-files              firefox:etc-firefox-policies    :system-files                    -
system-packages-doc       firefox:system-packages-doc     :system-packages-doc             -
u2f-devices               firefox:u2f-devices             :u2f-devices                     -
unity7                    firefox:unity7                  :unity7                          -
upower-observe            firefox:upower-observe          :upower-observe                  -
wayland                   firefox:wayland                 :wayland                         -
x11                       firefox:x11                     :x11                             -
```

I notice the `personal-files`connexion for firefox which look promising ([see doc](https://snapcraft.io/docs/personal-files-interface)).
So I tried : 
```snap connect mysql-workbench-community:personal-files```
> erreur : snap "mysql-workbench-community" has no plug named "personal-files"

Maybe there is something to change on the snap package in order to add this endpoint ?

Bests regards

**Comment by tonybolzan** [comment]
`personal-files` are defined in snap config on build time. But we need to specify a specific directory to read or write, this are not your case.
- https://snapcraft.io/docs/personal-files-interface

I don't know if your problem are related to snap or directly to MySQL Workbench.
I will try reproduce this behavior in the next days.

**Comment by AnaelMobilia** [comment]
For information, I haven't this issue with the latest version (8.0.29) of Oracle MySQL Workbench on a computer installed on Ubuntu 20.04 then migrated on 22.04.
Installing directly Oracle MySQL Workbench on an Ubuntu 22.04 isn't an available option due to dependencies issues.

I'm staying available if you need more details or tests.

Bests regards

**Comment by tonybolzan** [comment]
I validated this environment but with **Ubuntu 21.10** and **Snap 2.54.4** with the mounted sshfs and 755 dir permission.
I don't get any errors or warnings.

Additionally I built 8.0.29 on the edge channel.
Test with `sudo snap install mysql-workbench-community --edge`

**Comment by AnaelMobilia** [comment]
Thanks for the update !

I used the latest (edge) version but the issue is still present.
Maybe related to more recent version of Ubuntu (22.04) and snap (2.55.3+22.04ubuntu1) ?

Tell me if you need more information / tests

Bests regards

**Comment by tonybolzan** [comment]
I haven't upgraded to Ubuntu 22.04 yet, so I haven't been able to do more testing.
But SSHFS has been discontinued, and perhaps you should look into other alternatives specifically for sharing disks.

- https://news.ycombinator.com/item?id=31812506 Sshfs Is Orphaned
- https://github.com/libfuse/sshfs This repository has been archived by the owner. It is now read-only.

**Comment by tonybolzan** [comment]
I can't reproduce the problem
